server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_threate
    username: root
    password: 2354655615
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

  #??????
  mail:
    #??smtp??????
    # qq???smtp.qq.com          ???465?587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       ???465?994
    host: smtp.qq.com
    #?????
    username: 2354655615@qq.com
    #????,?????????????????????
    password: ipsdvrtmwyxpebbc
    #???465?587
    port: 587
    #????????UTF-8
    default-encoding: UTF-8
    #????
    properties:
      mail:
        #??SSL ????
        smtp:
          ssl:
            #????????ssl
            enable: false
            required: false
          #??debug??????????????????????????????
        debug: false

